export default {
  // private
  // overview: '/overview',
  // overviewTwo: '/overview/two',
  // overviewThree: '/overview/three',
  invoices: "/invoices",
  invoiceInfo: "/invoice-info",
  invoicedownload: "/download-invoice",
  products: "/products",
  productInfo: "/Product-info",
  scheme: "/scheme-claims",
  ClaimInfo: "/claim-info",
  customers: "/customers",
  customerInfo: "/customer-info",
  customerDetails: "/customer-details",
  complaints:"/complaints",
  complaintInfo:"/complaint-info",
  newComplaint:"/new-complaint",
  orders:"/orders",
  orderdtl:"/orders/order-dtl",
  invoicedtl:"/orders/invoice-info",
  profile: "/profile",
  DashboardComponent: "/dashboard",
  home: "/home",
  schemes: "/schemes",
  schemeInfo: "/scheme-info",
  ordersList: "/orders",
  newOrders: "/new-order",
  viewCart: "/view-cart",
  profileData: '/profile-data',
  stockStatus: '/stock-status',
  outsstanding: '/outstanding',


  // auth
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot_password",
};
